apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scp-bz-certificate
  namespace: cert-manager
spec:
  secretName: scp-bz-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: scp.bz
  dnsNames:
    - scp.bz
