apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: makoto-certificate
  namespace: cert-manager
spec:
  secretName: makoto-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: makoto.tharp.io
  dnsNames:
    - makoto.tharp.io
