apiVersion: v2
name: cert-manager
description: Cloud-native certificate manager featuring Let's Encrypt integration
version: 1.0.0
dependencies:
    - name: cert-manager
      version: 1.8.0
      repository: https://charts.jetstack.io
