apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'cert-manager-routes'
  namespace: 'gloo-system'
spec:
  routes:
    - matchers:
        - prefix: /.well-known/acme-challenge/
      routeAction:
        single:
          kube:
            ref:
              name: acme-solver
              namespace: cert-manager
            port: 8089
